### ISSUE TITLE
The pretrained model performance is worse than the paper claimed

### ISSUE THREAD

**Issue by Godricly** [mjq11302010044/RRPN#1]
Hi, 
  I tested your pretrained VGG 16 model on ICDAR2015 with no parameters change. The following is the result of icdar2015 official evaluation script. All these values are lower than what is claimed in the paper.
```
Calculated!{"recall": 0.6721232546942706, "precision": 0.7977142857142857, "hmean": 0.7295531748105567, "AP": 0}
```

**Comment by mjq11302010044** [comment]
Hi @Godricly , your image scale may not be well set, you can set a larger input scale of a testing image, e.g. with (height / width) of (1000 / 1700) or larger, this can help with a performance gain, but this model is not our best model yet :)
