### ISSUE TITLE
tools/test_net.py has no rt_test_net() function

### ISSUE THREAD

**Issue by afterimagex** [mjq11302010044/RRPN#2]
cannot import name rt_test_net
tools/test_net.py need call rt_test_net function in lib/rotation/rt_test.py
but not find it

**Comment by mjq11302010044** [comment]
@afterimagex rt_test is not implemented, if you want to do some testing, you need to implement yourself by using some functions in tools/rotation_demo.py (e.g. demo() or rotation_demo()), some examples is in tools/joint_test.py, hope it will help.

**Comment by afterimagex** [comment]
thanks a lot!
