### ISSUE TITLE
Demo on CPU

### ISSUE THREAD

**Issue by idefix92** [mjq11302010044/RRPN#3]
Thank you for your great work! I wanted kindly to ask if there is an option to run the demo on CPU only? :) 

Best Regards

Valentin

**Comment by mjq11302010044** [comment]
@idefix92  hi~，I feel sorry for that we didn't organize a pipeline for CPU-only version. Because the skew-rectangle IoU computation is too slow for CPU. The CPU version we adopted is in python-opencv package. You can replace our cuda function with that, and maybe python nms is needed. (The python sample of skew_NMS is provided in $RRPN_ROOT/lib/rotation/rotate_cpu_nms.py)

**Comment by idefix92** [comment]
@mjq11302010044 thank you very much for your answer. I suppose it is better to run it on GPU I took an AWS for few hours to see how it goes. The point is that I am getting an error when compiling the shipped caffe.  I have compiled "caffe-fast-rcnn" few times before and I some algorithms using it. 

Once I run yours I receive the error:

LD -o .build_release/lib/libcaffe.so.1.0.0
AR -o .build_release/lib/libcaffe.a
/usr/bin/ld: cannot find -lhdf5_serial_hl
/usr/bin/ld: cannot find -lhdf5_serial
collect2: error: ld returned 1 exit status
make: *** [.build_release/lib/libcaffe.so.1.0.0] Error 1


and I also tried to figure it out on the web, however, none of the advice has helped so far. Any ideas? Never had this issue with another caffe so far .. :/

**Comment by mjq11302010044** [comment]
@idefix92 Hi~, maybe you don't need to add 'serial' to -lhdf5_hl and -lhdf5

**Comment by idefix92** [comment]
Oh, well .. I have never done. I am just compiling als in the README :/ what should I modify there? I am careful with modifying your files.

**Comment by mjq11302010044** [comment]
@idefix92 Oh, that may be something wrong with the reload() function on cv2, the code may alright while removing or commenting that line.(But we didn't get this error before when using it :)

**Comment by mjq11302010044** [comment]
@idefix92  Or make sure if you have the cv2 package

**Comment by idefix92** [comment]
Okay, I will try to remove it :) Thank you! I have the cv2 package. Version 3.3.0 for python 2.7.

**Comment by mjq11302010044** [comment]
@idefix92 Okay, again thx for your interest in our project, and more questions about our project are welcome :)

**Comment by idefix92** [comment]
@mjq11302010044  I don't want to disturb too much but would be glad if you tell me which version of opencv you are using. :)

**Comment by mjq11302010044** [comment]
@idefix92 Welp, either opencv2 or opencv3 is okay I think.

**Comment by huishaoli** [comment]
> @idefix92 Oh, that may be something wrong with the reload() function on cv2, the code may alright while removing or commenting that line.(But we didn't get this error before when using it :)

Hello, Do you solve this problem?
