### ISSUE TITLE
Training Speed and Iteration Count

### ISSUE THREAD

**Issue by gyaliniz** [mjq11302010044/RRPN#35]
Helo @mjq11302010044. I'm trying to create a model on my own just like your trained model that you shared. 

But the training speed is very low.  The iteration speed is aroud 5 seconds and the iteration count is 490000. 

Do you have any trick to speed up the training speed? 
What can be the least iteration count to get the demo works?

**Comment by mjq11302010044** [comment]
@gyaliniz We are using Cuda 8 + Cudnn 5 in a Titan X, and this configuration can have ~1iter / s with input of (1000, 1700)
And in fact you can have a pretty good visualization after nearly 50K iters
