### ISSUE TITLE
required GPU Memory?

### ISSUE THREAD

**Issue by idefix92** [mjq11302010044/RRPN#4]
@mjq11302010044 I finally managed to run it :) thank you for your great support.
I do not have cuDNN installed ... that might be an issue with the memory required by the demo? 
I am using a fairly new GPU, NVIDIA QUADRO-M4000 with 8GB! How is it possible I am running out of Memory? Also, I've resized your images, but still...:

libprotobuf WARNING google/protobuf/io/coded_stream.cc:505] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.

Loaded network /home/vale/masterarbeit/H_AOSTD/data/faster_rcnn_models/vgg16_faster_rcnn.caffemodel
F1109 05:23:29.260838 22269 syncedmem.cpp:64] Check failed: error == cudaSuccess (2 vs. 0)  out of memory

I guess I could optimize utilization with cuDNN. But is it necessary? Quite bad experience with cuDNN...

**Comment by mjq11302010044** [comment]
@idefix92 It has some problems when run in Cuda 8 without cudnn 5, so we recommand cudnn installation, the cost of GPU memory will be much less :)

**Comment by idefix92** [comment]
@mjq11302010044  Great! Works with cuDNN amazing. Thank you very much for your work and efforts. I have one very last question. I saw that the BBOXES are saved as TXT files but do you also save the pictures with the bounding boxes drawn on them somewhere?  :)

**Comment by mjq11302010044** [comment]
@idefix92 Sorry, but we didn't implement that..

**Comment by mjq11302010044** [comment]
@idefix92 Also, we have some visualization example in tools/rotation_demo.py or lib/rotation/data_extractor.py :)
