### ISSUE TITLE
GT框的倾斜角θ的输入

### ISSUE THREAD

**Issue by mltloveyy** [mjq11302010044/RRPN#57]
你好。
请问在读取VOC数据集的时候，倾斜角θ是如何读入的？
我查看了datasets/pascal_voc.py/_load_pascal_annotation，跟faster-rcnn一样，读取的只有bndboxxmin, xmax, ymin, ymax，并没有倾斜角θ的读取。
所以，请问是如何输入GT框的倾斜角θ的？

**Comment by mjq11302010044** [comment]
请参照ReadMe当中的说明补充函数，目前caffe repo并不支持pascal_voc格式的读取。

mltloveyy <notifications@github.com> 于2020年10月22日周四 上午11:34写道：
