### ISSUE TITLE
数据集的标注格式是怎么样的？

### ISSUE THREAD

**Issue by yunren** [mjq11302010044/RRPN#7]
大牛，您好，我想用您的这个方法来检测一般的类似矩形目标，请问数据集的标注格式是什么样的啊？有没有专用的工具来制作，谢谢

**Comment by mjq11302010044** [comment]
你标注任意四个点也行，但是最后能够拟合成带朝向的矩形（x, y, h, w, theta）就可以了，我们在训练自己的任务时不需要标注数据，所以并未用到标注工具

**Comment by yunren** [comment]
好的，谢谢您的回复
